#!/bin/sh -e

TMP=build/tmp
RELEASE=build/releases

rm -fr build
mkdir -p ${TMP} ${RELEASE}

arch=64
if [ -n "$1" ]; then
    arch=$1
fi

version=$2
if [ ! -n "$2" ]; then
    version=$( wget https://turtlapp.com/download -O build/turtlhome > /dev/null 2>&1 && cat build/turtlhome | grep "linux$arch"|uniq| grep -oE "v.*/"|sed 's/v//g;s/\///g' )
fi

echo "* Retrieve artifact ${arch} ${version} ..."
[ -f /tmp/turtl-linux${arch}.tar.bz2 ] || wget -O /tmp/turtl-linux${arch}.tar.bz2 https://github.com/turtl/desktop/releases/download/v${version}/turtl-${version}-linux${arch}.tar.bz2

echo "* Extract tar ..."
tar xf /tmp/turtl-linux${arch}.tar.bz2 -C build

echo "* Prepare package directory ..."
mkdir -p ${TMP}/usr/share/turtl
cp -R build/turtl-linux${arch}/turtl/* ${TMP}/usr/share/turtl

echo "* Create icon ..."
mkdir -p ${TMP}/usr/share/pixmaps
mv build/turtl-linux${arch}/turtl/icon.png ${TMP}/usr/share/pixmaps/turtl.png

echo "* Create menu entry ..."
mkdir -p ${TMP}/usr/share/applications
cat > ${TMP}/usr/share/applications/turtl.desktop <<EOF
[Desktop Entry]
Name=Turtl
GenericName=Secure notes
Comment=Private notes and bookmarks with collaboration.
Exec=/usr/share/turtl/turtl
Icon=turtl
Type=Application
Terminal=false
Categories=Network;Application;
Keywords=secure;security;privacy;private;notes;bookmarks;collaborate;research;
StartupNotify=true
EOF

echo "* Copy content ..."
cp -r build/turtl-linux${arch}/turtl/* ${TMP}/usr/share/turtl

echo "* Create debian package ..."
size=$(du -cs ${TMP} | sed '1!d' | grep -oe "^[0-9]*")
[ "$arch" = 64 ] && architecture="amd64"
[ "$arch" = 32 ] && architecture="i386"

mkdir -p ${TMP}/DEBIAN
cat > ${TMP}/DEBIAN/control <<EOF
Package: turtl
Version: ${version}
License: GPLv3
Vendor: Lyon Bros. Enterprises, LLC
Architecture: ${architecture}
Maintainer: info@turtlapp.com
Installed-Size: ${size}
Section: default
Priority: extra
Homepage: https://turtlapp.com
Description: Private notes and bookmarks with collaboration.

EOF

fakeroot dpkg-deb -b -z9 ${TMP} ${RELEASE}

echo done
