#!/bin/sh

set -e

[ $(which fpm) ] || echo "Install fpm first. https://github.com/jordansissel/fpm/wiki"

TMP=/tmp/turtldeb
TMP_DEB=$TMP/deb

rm -fr $TMP
mkdir -p $TMP_DEB

cd /tmp

arch=64
if [ -n "$1" ]; then
        arch=$1
fi

version=$( wget https://turtl.it -O qturtlhome > /dev/null 2>&1 && cat turtlhome | grep -oE "turtl-linux64-[0-9].[0-9].[0-9]" | uniq | grep -Eo "[0-9].[0-9].[0-9]*$" )
if [ -n "$2" ]; then
	version=$2
fi

echo Retrieving artifact $arch $version ...
[ -f /tmp/turtl-linux$arch-version.tar.bz2 ] || wget https://turtl.it/releases/desktop/turtl-linux$arch-$version.tar.bz2

echo Extracting tar ...
tar xvf /tmp/turtl-linux$arch-$version.tar.bz2 -C $TMP > /dev/null 2>&1

echo Preparing package directory ...
mkdir -p $TMP_DEB/usr/share/turtl
cp -R $TMP/turtl-linux$arch/turtl/* $TMP_DEB/usr/share/turtl

echo Moving icon ...
mkdir -p $TMP_DEB/usr/share/pixmaps
mv $TMP_DEB/usr/share/turtl/icon.png $TMP_DEB/usr/share/pixmaps/turtl.png

echo Fix files permisions ...
chmod 0644 $TMP_DEB/usr/share/turtl/*
chmod 0755 $TMP_DEB/usr/share/turtl/turtl $TMP_DEB/usr/share/turtl/turtl-bin $TMP_DEB/usr/share/turtl/chromedriver $TMP_DEB/usr/share/turtl/nacl* $TMP_DEB/usr/share/turtl/nwjc $TMP_DEB/usr/share/turtl/payload
chmod 0755 $TMP_DEB/usr/share/turtl/locales $TMP_DEB/usr/share/turtl/lib $TMP_DEB/usr/share/turtl/pnacl
chmod 0644 $TMP_DEB/usr/share/turtl/locales/* $TMP_DEB/usr/share/turtl/pnacl/*
chmod 0755 $TMP_DEB/usr/share/turtl/lib/*

echo Creating menu entry ...
mkdir -p $TMP_DEB/usr/share/applications
cat > $TMP_DEB/usr/share/applications/turtl.desktop <<EOF
[Desktop Entry]
Name=Turtl
GenericName=Secure notes
Comment=Private notes and bookmarks with collaboration.
Exec=/usr/share/turtl/turtl
Icon=turtl
Type=Application
Terminal=false
Categories=Network;Application;
Keywords=secure;security;privacy;private;notes;bookmarks;collaborate;research;
StartupNotify=true
EOF

echo Creating debian package ...
cd $TMP
$(which fpm) -s dir -t deb -n turtl -v $version --license GPLv3 --vendor "Lyon Bros. Enterprises, LLC" --maintainer info@turtl.it --url https://turtl.it --description "Private notes and bookmarks with collaboration." deb/=/

echo
echo Package created in $TMP
echo
